version: '3'
services:
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Nautica
      POSTGRES_DB: platform_dev

volumes:
  db_data:
